updating bleurt placeholder with the model
learlab/textbook-summary-api pull request #17
Opened 2023-08-14 03:25 UTC by vaiibhavgupta

Python files to inference using BLEURT have been added.

@jchoi92k will add the model because I was facing permission issues and was unable to push from jupyterhub or my local.

FYI, the optimal threhosld for this model is 0.6 as mentioned on line 8 of src/answer_eval.py file.

2023-08-14 13:57 UTC, langdonholmes requested changes
Vaibhav, thanks for your work on this. We have a ways to go before this can be merged.

- Use PyTorch instead of Tensorflow.
- It looks like you copy/pasted some code into assets. This code contains a bunch of checks and functionality that our system will never use, which increases the complexity of our codebase for no benefit. This won't work. You may either rewrite the code in a simpler form, using Pytorch, or alternatively, you can find a version of the code that runs on PyTorch and import that to your scoring script. You should also add this to requirements.txt.
- Please document and add any added requirements to requirements.txt
- Please confirm that the image will build before requesting review. You can test this by running the docker build command. As is, this pull request will not build.
- Large assets are handled by the download_models.py file. The BLEURT model should be uploaded somewhere (probably Huggingface), and you will need to modify download_models.py to fetch the model.

2023-08-14 13:57 UTC, langdonholmes commented on src/answer_eval.py
> +from bleurt import score as score_lib
from bleurt.score import BleurtScorer

2023-08-14 13:57 UTC, langdonholmes commented on src/answer_eval.py
> +        self.bleurt_scorer = score_lib.BleurtScorer(str(Path("assets/bleurt")))
self.bleurt_scorer = BleurtScorer(str(Path("assets/bleurt")))

2023-08-15 01:31 UTC, vaiibhavgupta commented on assets/bleurt/score.py
Like create a new folder "pipelines" in "textbook-summary-api" and put this "score.py" in there?

2023-10-24 00:41 UTC, langdonholmes commented
I think this feature was added with a different PR

2023-10-24 00:41 UTC, closed without merging