Semantic similarity
learlab/textbook-summary-api pull request #6
Opened 2022-12-02 01:19 UTC by wesleygmorris

Adding the semantic similarity code and assets to the code.

2022-12-02 01:32 UTC, langdonholmes requested changes
Use a [context manager](https://realpython.com/python-with-statement/) when opening a file.

This type of code comment is not helpful. `# A function to tokenize the text` does not help anyone to understand what `tokenize_text()` does.

Your might want to use your comments to clarify what your code expects to find in "source_dict_path" and what `getSimilarity` expects from the "summary" and "chapter" arguments (string types).

Your two functions have different naming styles. I use snake case for functions and camelCase for classes. Just a style thing, but still. 

You are importing `stopwords `but not using it. I would prefer that we DO use `stopwords` instead of `if len(word) <2:`

2022-12-02 01:37 UTC, langdonholmes requested changes
create an `assets` directory and put data files there instead of in `models`.

`models` is for Pydantic data model definitions, not for Gensim or PyTorch models or what have you.

2022-12-02 01:38 UTC, langdonholmes requested changes
assets/ not src/assets/

2022-12-02 01:54 UTC, langdonholmes commented on src/sem_similarity.py
> +model_path = './assets/doc2vec_model'
model_path = '../assets/doc2vec_model'

2022-12-02 01:54 UTC, langdonholmes commented on src/sem_similarity.py
> +source_dict_path = './assets/macroeconomics_2e_section.json'
source_dict_path = '../assets/macroeconomics_2e_section.json'

2022-12-02 01:55 UTC, langdonholmes commented on src/sem_similarity.py
> +    for sent in nltk.sent_tokenize(text):
Why are you using the sentencizer?

2022-12-06 23:57 UTC, qiushiyan commented on src/sem_similarity.py
> +            tokens.append(word.lower())
This condition can be inverted

```py
if len(word) >= 2:
    tokens.append(word.lower())
```

2022-12-07 00:03 UTC, qiushiyan commented on src/sem_similarity.py
> +        for word in nltk.word_tokenize(sent):
This could be a small thing but if nltk has a vectorized version it's preferred to not use a manual for loop for going over all the sentences.

2022-12-07 00:06 UTC, qiushiyan commented
Looks like these functions havn't been added to the API routes yet, let me know if you need help with that.

2022-12-07 18:37 UTC, langdonholmes commented on src/sem_similarity.py
> +        for word in nltk.word_tokenize(sent):
I am not aware of any method to vectorize this process with NLTK

One possible method would be to use a list comprehension. I know the Python interpreter has some optimizations for list comprehensions, but I am not sure if this would actually improve performance...

`tokens = [tok for tok in nltk.word_tokenize(sent) if tok not in stopwords]`

2022-12-07 21:50 UTC, langdonholmes approved these changes

2022-12-07 22:09 UTC, langdonholmes commented
@qiushiyan 
Could you give this a once over and merge the pull request if it is acceptable? Once you merge, one of us will need to accept the cloudbuild and verify that everything is working with the new Docker image.

Highlights:
- **API expects a chapter number and a section number** instead of the full section text.
- The **/score call now returns 4 distinct floating point values** in most cases. See the SummaryResults model.
- download_models.py created for development purposes. this script is also called by the DockerFile.

2022-12-09 18:27 UTC, merged